[project]
name = "qwen3-4b-instruct-chat-cli"
version = "0.1.0"
description = "Example repository of using qwen3-4b-instruct-chat model in a command line interface."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
